/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Todo API
 * 할 일 목록을 관리하기 위한 간단한 연습용 API입니다.
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

import type { Todo } from "../model";

export const getGetTodosResponseMock = (): Todo[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    title: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    completed: faker.helpers.arrayElement([
      faker.datatype.boolean(),
      undefined,
    ]),
    createdAt: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().slice(0, 19)}Z`,
      undefined,
    ]),
  }));

export const getPostTodosResponseMock = (
  overrideResponse: Partial<Todo> = {},
): Todo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  title: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  createdAt: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().slice(0, 19)}Z`,
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetTodosIdResponseMock = (
  overrideResponse: Partial<Todo> = {},
): Todo => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  title: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  createdAt: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().slice(0, 19)}Z`,
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetTodosMockHandler = (
  overrideResponse?:
    | Todo[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Todo[]> | Todo[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/todos",
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetTodosResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPostTodosMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Todo> | Todo),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/todos",
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPostTodosResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetTodosIdMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Todo> | Todo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/todos/:id",
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetTodosIdResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getPutTodosIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/todos/:id",
    async (info) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getDeleteTodosIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/todos/:id",
    async (info) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};
export const getTodoAPIMock = () => [
  getGetTodosMockHandler(),
  getPostTodosMockHandler(),
  getGetTodosIdMockHandler(),
  getPutTodosIdMockHandler(),
  getDeleteTodosIdMockHandler(),
];
