FROM python:3.12-slim

WORKDIR /app
RUN mkdir -p input
RUN mkdir -p output

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
