spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: a-service
          uri: http://localhost:8081
          predicates:
            - Path=/a-service/**
          filters:
            - RewritePath=/a-service/(?<path>.*),/$\{path}
        - id: b-service
          uri: http://localhost:8082
          predicates:
            - Path=/b-service/**
          filters:
            - RewritePath=/b-service/(?<path>.*),/$\{path}