/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Todo API
 * 할 일 목록을 관리하기 위한 간단한 연습용 API입니다.
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import * as axios from "axios";

import type { Todo, TodoCreate } from "../model";

/**
 * @summary 모든 할 일 목록 조회
 */
export const getTodos = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Todo[]>> => {
  return axios.default.get(`/todos`, options);
};

export const getGetTodosQueryKey = () => {
  return [`/todos`] as const;
};

export const getGetTodosQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({
    signal,
  }) => getTodos({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTodos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTodosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodos>>
>;
export type GetTodosQueryError = AxiosError<unknown>;

export function useGetTodos<
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTodos<
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTodos<
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 할 일 목록 조회
 */

export function useGetTodos<
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTodosQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 새로운 할 일 추가
 */
export const postTodos = (
  todoCreate: TodoCreate,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Todo>> => {
  return axios.default.post(`/todos`, todoCreate, options);
};

export const getPostTodosMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTodos>>,
    TError,
    { data: TodoCreate },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTodos>>,
  TError,
  { data: TodoCreate },
  TContext
> => {
  const mutationKey = ["postTodos"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTodos>>,
    { data: TodoCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postTodos(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTodosMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTodos>>
>;
export type PostTodosMutationBody = TodoCreate;
export type PostTodosMutationError = AxiosError<unknown>;

/**
 * @summary 새로운 할 일 추가
 */
export const usePostTodos = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTodos>>,
      TError,
      { data: TodoCreate },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTodos>>,
  TError,
  { data: TodoCreate },
  TContext
> => {
  return useMutation(getPostTodosMutationOptions(options), queryClient);
};

/**
 * @summary 특정 할 일 상세 조회
 */
export const getTodosId = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Todo>> => {
  return axios.default.get(`/todos/${id}`, options);
};

export const getGetTodosIdQueryKey = (id: number) => {
  return [`/todos/${id}`] as const;
};

export const getGetTodosIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodosId>>,
  TError = AxiosError<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodosIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodosId>>> = ({
    signal,
  }) => getTodosId(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTodosId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTodosIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodosId>>
>;
export type GetTodosIdQueryError = AxiosError<void>;

export function useGetTodosId<
  TData = Awaited<ReturnType<typeof getTodosId>>,
  TError = AxiosError<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodosId>>,
          TError,
          Awaited<ReturnType<typeof getTodosId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTodosId<
  TData = Awaited<ReturnType<typeof getTodosId>>,
  TError = AxiosError<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodosId>>,
          TError,
          Awaited<ReturnType<typeof getTodosId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTodosId<
  TData = Awaited<ReturnType<typeof getTodosId>>,
  TError = AxiosError<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 특정 할 일 상세 조회
 */

export function useGetTodosId<
  TData = Awaited<ReturnType<typeof getTodosId>>,
  TError = AxiosError<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTodosIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary 기존 할 일 수정
 */
export const putTodosId = (
  id: number,
  todoCreate: TodoCreate,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.put(`/todos/${id}`, todoCreate, options);
};

export const getPutTodosIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTodosId>>,
    TError,
    { id: number; data: TodoCreate },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTodosId>>,
  TError,
  { id: number; data: TodoCreate },
  TContext
> => {
  const mutationKey = ["putTodosId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTodosId>>,
    { id: number; data: TodoCreate }
  > = (props) => {
    const { id, data } = props ?? {};

    return putTodosId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutTodosIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTodosId>>
>;
export type PutTodosIdMutationBody = TodoCreate;
export type PutTodosIdMutationError = AxiosError<unknown>;

/**
 * @summary 기존 할 일 수정
 */
export const usePutTodosId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTodosId>>,
      TError,
      { id: number; data: TodoCreate },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTodosId>>,
  TError,
  { id: number; data: TodoCreate },
  TContext
> => {
  return useMutation(getPutTodosIdMutationOptions(options), queryClient);
};

/**
 * @summary 할 일 삭제
 */
export const deleteTodosId = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/todos/${id}`, options);
};

export const getDeleteTodosIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTodosId>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTodosId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteTodosId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTodosId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTodosId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTodosIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTodosId>>
>;

export type DeleteTodosIdMutationError = AxiosError<unknown>;

/**
 * @summary 할 일 삭제
 */
export const useDeleteTodosId = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTodosId>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTodosId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteTodosIdMutationOptions(options), queryClient);
};
