spring:
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: "authorization_code"
            redirect-uri: "{baseUrl}/login/oauth2/code/azure"
            client-authentication-method: 'client_secret_post'
            scope:
              - "openid"
              - "profile"
        provider:
          azure:
            authorization-uri: "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize"
            token-uri: "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
            jwk-set-uri: "https://login.microsoftonline.com/organizations/discovery/v2.0/keys"
