CREATE TABLE todos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    completed   BOOLEAN NOT NULL DEFAULT FALSE,
    priority    VARCHAR(10) NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT todos_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX idx_todos_completed ON todos (completed);
CREATE INDEX idx_todos_due_date ON todos (due_date);

INSERT INTO todos (title, description, completed, priority, due_date, created_at, updated_at)
SELECT
    'Todo ' || number,
    'Initial todo item number ' || number,
    number % 4 = 0,
    CASE number % 3
        WHEN 0 THEN 'HIGH'
        WHEN 1 THEN 'MEDIUM'
        ELSE 'LOW'
    END,
    CURRENT_DATE + (number % 30),
    CURRENT_TIMESTAMP - ((100 - number) * INTERVAL '1 hour'),
    CURRENT_TIMESTAMP - ((100 - number) * INTERVAL '1 hour')
FROM generate_series(1, 100) AS number;
