spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-authentication-method: client_secret_post
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/callback/"
            scope:
              - profile
              - email
