version: '3.8'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  pc-backend:
    container_name: pc-backend
    build:
      context: ./action-in-blog-pc
  mobile-backend:
    container_name: mobile-backend
    build:
      context: ./action-in-blog-mobile
