version: "3.9"
services:
  redis:
    image: redis
    command: redis-server --requirepass some-password --port 6379
    container_name: redis-server
    ports:
      - '6379:6379'
  backend-1:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: on-failure
  backend-2:
    build: .
    ports:
      - '8081:8080'
    depends_on:
      - redis
    restart: on-failure