apiVersion: v1
kind: Namespace
metadata:
  name: foo-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: bar-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-foo
  namespace: foo-ns
spec:
  hard:
    pods: "5"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
