apiVersion: v1
kind: Pod
metadata:
  name: foo-pod
  namespace: bar-ns
  labels:
    app: foo-app
spec:
  containers:
    - name: foo-container
      image: opop3966/ns-poc
      env:
        - name: SERVICE_NAME
          value: foo-pod-in-bar-ns
---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
  namespace: bar-ns
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: foo-app
