apiVersion: v1
kind: Pod
metadata:
  name: qux-pod
  namespace: foo-ns
  labels:
    app: qux-app
spec:
  containers:
    - name: qux-pod
      image: opop3966/ns-poc
      env:
        - name: SERVICE_NAME
          value: qux-pod-in-foo-ns
      resources:
        requests:
          memory: 2Gi
          cpu: "2"
        limits:
          memory: 2Gi
          cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: qux-service
  namespace: foo-ns
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: qux-app
