apiVersion: v1
kind: Pod
metadata:
  name: foo-pod
  namespace: foo-ns
  labels:
    app: foo-app
spec:
  containers:
    - name: foo-container
      image: opop3966/ns-poc
      env:
        - name: SERVICE_NAME
          value: foo-pod-in-foo-ns
      resources:
        requests:
          memory: 2Gi
          cpu: "2"
        limits:
          memory: 2Gi
          cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
  namespace: foo-ns
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: foo-app
  type: NodePort